apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: postgres-health-check
  namespace: monitoring
  labels:
    release: monitoring  # Must match your Prometheus label (you said you use 'monitoring')
spec:
  jobName: postgres-health
  prober:
    url: blackbox-prometheus-blackbox-exporter.monitoring.svc:9115
  module: tcp_connect  # <--- This is the key change (TCP instead of HTTP)
  targets:
    staticConfig:
      static:
      # FORMAT: <Service-Name>.<Namespace>.svc:5432
      - app-db-rw.default.svc.cluster.local:5432
  interval: 30s
