apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: ticketing-app
  labels:
    app: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --no-autoupdate
        - run
        - --token=eyJhIjoiYzcxMWQyOWM1ODQyNTFkOTQ0NjZkNGI5OTc5Mjk4OWIiLCJ0IjoiNWZiMTcwNTUtODllMy00NGFhLTkzNjAtYjgzZDhmNDdiZmM4IiwicyI6Ik56bGxPV1poWVRNdFpUVmpPUzAwWTJZd0xUZ3hNamd0TmpSalpUVTNPVEF3WkRSaSJ9
