---
- name: Final Cluster Validation
  hosts: master
  become: yes
  vars:
    TOTAL_NODES: "{{ groups['master'] | length + groups['workers'] | length }}"
    POD_NAME_PREFIX: "ticketing-app-"
    HEALTH_CHECK_URL: "http://localhost:5000/health"

  tasks:
    - name: Wait until all nodes are Ready
      shell: |
        export KUBECONFIG=/etc/kubernetes/admin.conf
        echo "Checking nodes..."
        READY_NODES=0
        while [ $READY_NODES -lt {{ TOTAL_NODES }} ]; do
          READY_NODES=$(kubectl get nodes --no-headers 2>/dev/null | grep -c " Ready" || true)
          echo "Nodes Ready: $READY_NODES... waiting for {{ TOTAL_NODES }}"
          sleep 5
        done
        echo "All nodes are Ready!"
      args:
        executable: /bin/bash
      register: node_status
      changed_when: false
      failed_when: node_status.rc != 0

    # --- FIXED TASK: WAIT FOR POD ---
    - name: Get the name of the running pod (Wait up to 60s)
      shell: |
        export KUBECONFIG=/etc/kubernetes/admin.conf
        kubectl get pods -n ticketing-app --field-selector=status.phase=Running \
        --no-headers | grep "{{ POD_NAME_PREFIX }}" | awk 'NR==1{print $1}'
      args:
        executable: /bin/bash
      register: pod_name_result
      # Retry until we actually get a pod name (stdout is not empty)
      until: pod_name_result.stdout != ""
      retries: 12
      delay: 5
      changed_when: false

    - name: Debug Pod Name (Verify we found it)
      ansible.builtin.debug:
        msg: "Found App Pod: {{ pod_name_result.stdout }}"

    - name: Execute curl command inside the pod
      ansible.builtin.shell: |
        export KUBECONFIG=/etc/kubernetes/admin.conf
        
        # Run curl via kubectl using environment variables
        CURL_STATUS=$(kubectl exec -n ticketing-app $TARGET_POD -- curl -s -o /dev/null -w "%{http_code}" $TARGET_URL)
        
        if [ "$CURL_STATUS" == "200" ]; then
          echo "Health check successful (Status 200)."
          exit 0
        else
          echo "Health check failed (Status $CURL_STATUS)."
          exit 1
        fi
      environment:
        TARGET_POD: "{{ pod_name_result.stdout }}"
        TARGET_URL: "{{ HEALTH_CHECK_URL }}"
      args:
        executable: /bin/bash
      register: health_check_result
      changed_when: false

    - name: Display Health Check Result
      ansible.builtin.debug:
        msg: "Pod {{ pod_name_result.stdout }} health check status: {{ health_check_result.stdout }}"
      when: health_check_result is succeeded
