{
 "title": "Python-Application-Monitoring ",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) \r\n* 100 \r\n* on(instance) group_left(nodename) node_uname_info",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (\r\n  (\r\n    node_filesystem_avail_bytes{mountpoint=\"/\", fstype!=\"rootfs\"}\r\n    /\r\n    node_filesystem_size_bytes{mountpoint=\"/\", fstype!=\"rootfs\"}\r\n  ) * 100\r\n)\r\n* on(instance) group_left(nodename) node_uname_info",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (\r\n  avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100\r\n)\r\n* on(instance) group_left(nodename) node_uname_info",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  { "title": "Application Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Application Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"ticketing-app-health\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"ticketing-app-health\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"ticketing-app.*\", container!=\"\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod restart count",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{pod=~\"ticketing-app.*\"}) by (pod)\r\n  * on(pod) group_left(node)\r\n  kube_pod_info",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"ticketing-app.*\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tickets Stats",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_ticket_stats_count", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Priority Stats",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_priority_stats_count", "legendFormat": "{{priority}}" }
   ]
  },
  { "title": "DB Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "DB Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "probe_success", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "db cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "cor" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"app-db-.*\", container!=\"\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"app-db-.*\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Pod restart count",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 45 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{pod=~\"app-db-.*\"}) by (pod)\r\n  * on(pod) group_left(node)\r\n  kube_pod_info",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}